package connection;

public enum MessageType {
    REQUEST_BALLOT, RESPONSE_BALLOT, SEND_MESSAGE, SEND_VOTE, CONFIRMATION_VOTE, ALREADY_VOTED,
    CLOSING_CONNECTION, SEND_ELECTION, CONFIRM_ELECTION
}
